disabled_rules: # 기본 활성화된 룰 중에 비활성화할 룰을 지정
- trailing_whitespace

opt_in_rules: # 기본(default) 룰이 아닌 룰들을 활성화
 - empty_count
    
#included: # swiftlint 과정에 포함할 파일 경로
# - Source
    
excluded: # swiftlint를 적용하지 않게 설정할 파일 경로, `included`보다 우선순위 높음
- Ikdaman/App/AppDelegate.swift
- Ikdaman/App/SceneDelegate.swift
- Ikdaman/App/AppComponent.swift
- Ikdaman/App/AppCoordinator.swift

# 행 길이 커스텀 정의
line_length:
  ignores_urls: true                       # URL에 대해 행 길이 제한 미적용
  ignores_comments: true                   # 코멘트에 대해 행 길이 제한 미적용
  ignores_interpolated_strings: true       # 보간된 문자열 행 길이 제한 미적용

#correctable_rules: # 자동 수정할 규칙 지정
#- mark

